# Generated by Django 2.0.6 on 2018-06-20 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_auto_20180620_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finisher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
