# Generated by Django 2.0.6 on 2018-06-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_auto_20180620_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmembership',
            name='accepted',
        ),
    ]
